language: python
dist: xenial
python:
  - 2.7
  - 3.6
  - 3.7
  - 3.8
env:
  - DJANGO=2.0 DRF=3.9.x
  - DJANGO=2.1 DRF=3.9.x
  - DJANGO=2.2 DRF=3.9.x
  - DJANGO=3.0 DRF=3.9.x
  - DJANGO=2.0 DRF=3.10.x
  - DJANGO=2.1 DRF=3.10.x
  - DJANGO=2.2 DRF=3.10.x
  - DJANGO=3.0 DRF=3.10.x
  - DJANGO=2.0 DRF=3.11.x
  - DJANGO=2.1 DRF=3.11.x
  - DJANGO=2.2 DRF=3.11.x
  - DJANGO=3.0 DRF=3.11.x
install:
  - pip install -r requirements.dev.txt
  - pip install Django==$DJANGO
  - pip install djangorestframework==$DRF
script:
  - pytest
after_success:
  - codecov
