language: python
dist: xenial
python:
  - 3.6
  - 3.7
  - 3.8
env:
  - DJANGO=2.0 DRF=3.9.*
  - DJANGO=2.1 DRF=3.9.*
  - DJANGO=2.2 DRF=3.9.*
  - DJANGO=3.0 DRF=3.9.*
  - DJANGO=2.0 DRF=3.10.*
  - DJANGO=2.1 DRF=3.10.*
  - DJANGO=2.2 DRF=3.10.*
  - DJANGO=3.0 DRF=3.10.*
  - DJANGO=2.0 DRF=3.11.*
  - DJANGO=2.1 DRF=3.11.*
  - DJANGO=2.2 DRF=3.11.*
  - DJANGO=3.0 DRF=3.11.*
install:
  - pip install -r requirements.dev.txt
  - pip install Django==$DJANGO
  - pip install djangorestframework==$DRF
  - python manage.py makemigrations
  - python manage.py migrate
script:
  - pytest
after_success:
  - codecov
