language: python
dist: xenial
python:
  - 3.6
  - 3.7
  - 3.8
env:
  - DJANGO=2.0
  - DJANGO=2.1
  - DJANGO=2.2
  - DJANGO=3.0
  - DRF=3.9
  - DRF=3.10
  - DRF=3.11
install:
  - pip install -r requirements.dev.txt
  - pip install Django==$DJANGO
  - pip install djangorestframework==$DRF
script:
  - pytest
after_success:
  - codecov
