language: python
dist: bionic
python:
  - 3.7
  - 3.8
  - 3.9
env:
  - DJANGO=2.2.0 DRF=3.9.0
  - DJANGO=2.2.0 DRF=3.10.0
  - DJANGO=2.2.0 DRF=3.11.0
  - DJANGO=2.2.0 DRF=3.12.0
  - DJANGO=3.2.0 DRF=3.9.0
  - DJANGO=3.2.0 DRF=3.10.0
  - DJANGO=3.2.0 DRF=3.11.0
  - DJANGO=3.2.0 DRF=3.12.0
install:
  - pip install -q -r requirements.dev.txt
  - pip install -q django~=$DJANGO
  - pip install -q djangorestframework~=$DRF
script:
  - pytest
after_success:
  - codecov
